### ISSUE TITLE
How to unescape `:` in the beggining of a string key?

### ISSUE THREAD

**Issue by doronbehar** [memoryhole/jjo#4]
Among all implementations `jjo`, `njo`, `jo` etc. I'd like to use this one because I often need the ability to create arrays of objects. `jo` doesn't support that, see https://github.com/jpmens/jo/issues/63 but `jjo` does: https://github.com/memoryhole/jjo/blob/v1.0.3/README.md#create-array.

I'm having escaping issues. I'm trying to run:

```
$ jjo special_string=":ba"
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'ba'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at readFile (/var/lib/npm/lib/node_modules/jjo/dist/index.js:23:25)
    at parse (/var/lib/npm/lib/node_modules/jjo/dist/index.js:42:16)
    at pairs.forEach (/var/lib/npm/lib/node_modules/jjo/dist/index.js:59:20)
    at Array.forEach (<anonymous>)
    at Object.parseKeyValuePairs (/var/lib/npm/lib/node_modules/jjo/dist/index.js:58:11)
    at Command.commander_1.default.action (/var/lib/npm/lib/node_modules/jjo/dist/jjo.js:40:27)
    at Command.listener (/var/lib/npm/lib/node_modules/jjo/node_modules/commander/index.js:291:8)
    at Command.emit (events.js:198:13)
```

Naturally this happens because I'm supposed to use `:` as a prefix in order to make `jjo` read json files but I'd like to insert this string literally.

**Comment by doronbehar** [comment]
BTW the same goes for `@` at the beginning.

**Comment by memoryhole** [comment]
Nice find. If you are running in bash or equivalent, then you can execute:
```bash
$ jjo special_string=\":ba\"
{
    "special_string": ":ba"
}
```

**Comment by doronbehar** [comment]
Oh right, fair enough. It might worth pointing that out in the README, along with the fact that `:` `@` are treated as "get this key's contents from a file" which isn't trivial unless you are familiar with the original `jo`.

**Comment by memoryhole** [comment]
Yes that was definitely an omission. I've updated the README. Thanks!
